v4l2: Fix transfer function for HLG case
This patch correctly sets the transer function and fixes the below error
introduced by commit
0496ec844 v4l2: Add support for ARIB STD B67 (HLG) EOTF.

Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
0:00:00.111058237   916 0xaaab1cab5180 WARN                    v4l2 gstv4l2object.c:3764:gst_v4l2_object_set_format_full:<v4l2src0:src> Unknown colorimetry transfer 15
0:00:00.111171698   916 0xaaab1cab5180 WARN                    v4l2 gstv4l2object.c:3764:gst_v4l2_object_set_format_full:<v4l2src0:src> Unknown colorimetry transfer 15
0:00:00.111197900   916 0xaaab1c9be100 WARN                 v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixated !
0:00:00.111228774   916 0xaaab1cab5180 WARN                 default v4l2-utils.c:189:gst_v4l2_error:<v4l2src0> error: Device '/dev/video0' does not support interleaved interlacing
0:00:00.111262507   916 0xaaab1cab5180 WARN                 default v4l2-utils.c:192:gst_v4l2_error:<v4l2src0> error: Device wants progressive interlacing
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Device '/dev/video0' does not support interleaved interlacing
Additional debug info:
../git/sys/v4l2/gstv4l2object.c(4208): gst_v4l2_object_set_format_full (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
Device wants progressive interlacing
ERROR: pipeline doesn't want to preroll.
0:00:00.111522163   916 0xaaab1cab5180 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<v4l2src0> error: Internal data stream error.
Execution ended after 0:00:00.000486738
0:00:00.111556116   916 0xaaab1cab5180 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<v4l2src0> error: streaming stopped, reason not-negotiated (-4)
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
../git/libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
Freeing pipeline ...

Upstream-Status: Invalid [Xilinx Specific]
Signed-off-by: Vishal Sagar <vishal.sagar@xilinx.com>
Signed-off-by: Neel Gandhi <neel.gandhi@xilinx.com>

Acked-by:Varunkumar Allagadapa <varunkumar.allagadapa@xilinx.com>